version: '3.4'

x-studio-environment:
  &studio-environment
    MPLBACKEND: ps
    SHELL: /bin/bash
    AWS_S3_ENDPOINT_URL: http://minio:9000
    DATA_DB_HOST: postgres
    DJANGO_SETTINGS_MODULE: contentcuration.dev_settings
    RUN_MODE: docker-compose
    CELERY_TIMEZONE: America/Los_Angeles
    CELERY_REDIS_DB: 0
    CELERY_BROKER_ENDPOINT: redis
    CELERY_RESULT_BACKEND_ENDPOINT: redis
    CELERY_REDIS_PASSWORD: ""
    ELASTICSEARCH_HOST: elasticsearch

x-studio-worker:
  &studio-worker
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: learningequality/studio-app-dev
    depends_on:
      - minio
      - postgres
      - redis
    volumes:
      - .:/src
    environment: *studio-environment
    stdin_open: true
    tty: true

services:
  studio-app:
    <<: *studio-worker
    entrypoint: python docker/entrypoint.py
    command: yarn run devserver
    ports:
      - "8080:8080"

  celery-worker:
    <<: *studio-worker
    command: make celery_studio_worker

  indexing-worker:
    <<: *studio-worker
    command: make celery_indexing_worker

  minio:
    image: minio/minio
    entrypoint: minio server /data
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"

  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: learningequality
      POSTGRES_PASSWORD: kolibri
      POSTGRES_DB: kolibri-studio
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:4.0.9
  
  elasticsearch:
    image: elasticsearch:5.6


  cloudprober:
    <<: *studio-worker
    working_dir: /src/deploy
    command: /bin/cloudprober --config_file ./cloudprober.cfg
    # wait until the main app and celery workers have started
    depends_on:
      - studio-app
      - celery-worker
      - indexing-worker


volumes:
  minio_data:
  pgdata:
